services:
  database:
    image: postgres:14.18
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: bookly
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  - postgres_data:
      driver: local
